language: cpp
compiler:
  - gcc
  - clang

# Install required dependencies in the environment
install:
  - sudo apt-get update

# Before our script is run (setup build)
before_script:
  - mkdir build
  - cd build
  - cmake ..

# Run our build
script:
  - make
  - make test
