language: cpp
env:
  - COMPILER="gcc-4.8"
  - COMPILER="gcc-4.9"
  - COMPILER="clang-3.4"
  - COMPILER="clang-3.5"

# Setup repository sources before install
before_install:
  # Add toolchain for our GCC version checks
  - if [[ $COMPILER == gcc* ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [[ $COMPILER == gcc* ]]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

# Install our required dependencies
install:
  # gcc-4.8
  - if [[ "$COMPILER" = "gcc-4.8" ]]; then sudo apt-get install -qq g++-4.8; fi
  - if [[ "$COMPILER" = "gcc-4.8" ]]; then export CXX="g++-4.8"; fi

    # gcc-4.9
  - if [[ "$COMPILER" = "gcc-4.9" ]]; then sudo apt-get install -qq g++-4.9; fi
  - if [[ "$COMPILER" = "gcc-4.9" ]]; then export CXX="g++-4.9"; fi

  # clang 3.4
  - if [[ "$COMPILER" == "clang-3.4" ]]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [[ "$COMPILER" == "clang-3.4" ]]; then export CXX="clang++-3.4"; fi

  # clang 3.5
  - if [[ "$COMPILER" == "clang-3.5" ]]; then sudo apt-get install --allow-unauthenticated -qq clang-3.5; fi
  - if [[ "$COMPILER" == "clang-3.5" ]]; then export CXX="clang++-3.5"; fi

  # Catch
  - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - sudo mv catch.hpp /usr/local/include

# Before our script is run (setup build)
before_script:
  - mkdir build
  - cd build
  - cmake ..

# Run our build
script:
  - make
  - ./tests/test_nuclear
