language: cpp
compiler:
  - gcc:
    - 4.8
    - 4.9
  - clang

# Setup repository sources before install
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

# Install our required dependencies
install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

  # Catch
  - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - sudo mv catch.hpp /usr/local/include

# Before our script is run (setup build)
before_script:
  - mkdir build
  - cd build
  - cmake ..

# Run our build
script:
  - make
  - ./tests/test_nuclear
