language: cpp
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
    packages:
      - cmake
      - gcc-4.9
      - g++-4.9
      - gcc-5
      - g++-5
      - clang-3.5

env:
  - COMPILER="gcc-4.9"
  - COMPILER="gcc-5"
  - COMPILER="clang-3.5"

# Install our required dependencies
install:

  # gcc-4.9
  - if [[ "$COMPILER" == "gcc-4.9" ]]; then export CXX="g++-4.9"; fi
  - if [[ "$COMPILER" == "gcc-4.9" ]]; then export CC="gcc-4.9"; fi

  # gcc-5
  - if [[ "$COMPILER" == "gcc-5" ]]; then export CXX="g++-5"; fi
  - if [[ "$COMPILER" == "gcc-5" ]]; then export CC="gcc-5"; fi

  # clang 3.4
  - if [[ "$COMPILER" == "clang-3.4" ]]; then export CXX="clang++-3.4"; fi
  - if [[ "$COMPILER" == "clang-3.4" ]]; then export CC="clang-3.4"; fi

  # clang 3.5
  - if [[ "$COMPILER" == "clang-3.5" ]]; then export CXX="clang++-3.5"; fi
  - if [[ "$COMPILER" == "clang-3.5" ]]; then export CC="clang-3.5"; fi

  # Catch
  - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - mkdir -p /tmp/include
  - mv catch.hpp /tmp/include

# Before our script is run (setup build)
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCATCH_INCLUDE_DIR=/tmp/include ..

# Run our build
script:
  - make
  - ./tests/test_nuclear exclude:[network]
