language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - CXX_COMPILER=g++-5
        - CC_COMPILER=gcc-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CXX_COMPILER=g++-6
        - CC_COMPILER=gcc-6

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX_COMPILER=g++-7
        - CC_COMPILER=gcc-7

    - os: linux
      compiler: clang
      env:
        - CXX_COMPILER=clang++
        - CC_COMPILER=clang

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        - CXX_COMPILER=clang++-3.5
        - CC_COMPILER=clang-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        - CXX_COMPILER=clang++-3.6
        - CC_COMPILER=clang-3.6

install:
  # Catch
  - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - mkdir -p /tmp/include
  - mv catch.hpp /tmp/include

  - export CC=$CC_COMPILER
  - export CXX=$CXX_COMPILER

# Before our script is run (setup build)
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCATCH_INCLUDE_DIR=/tmp/include ..

# Run our build
script:
  - make
  - ./tests/test_nuclear exclude:[network]
